import os
import json
import subprocess
from typing import List, Dict, Any, Callable
from core.skill import Skill

class CodeGeneratorSkill(Skill):
    @property
    def name(self) -> str:
        return "code_generator_skill"

    def get_tools(self) -> List[Dict[str, Any]]:
        return [
            {
                "type": "function",
                "function": {
                    "name": "create_fullstack_website",
                    "description": "Create a complete full-stack website with frontend and backend. Automatically generates HTML, CSS, JavaScript, and backend code.",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "project_name": {"type": "string", "description": "Name of the website project"},
                            "description": {"type": "string", "description": "What the website should do (e.g., 'todo app', 'portfolio site', 'e-commerce store')"},
                            "tech_stack": {"type": "string", "description": "Technology preference: 'react', 'vue', 'vanilla', 'flask', 'express'", "default": "react"}
                        },
                        "required": ["project_name", "description"]
                    }
                }
            },
            {
                "type": "function",
                "function": {
                    "name": "create_python_app",
                    "description": "Create a Python application with all necessary files and dependencies",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "app_name": {"type": "string", "description": "Name of the Python application"},
                            "description": {"type": "string", "description": "What the app should do"},
                            "app_type": {"type": "string", "description": "Type: 'cli', 'gui', 'web', 'automation'"}
                        },
                        "required": ["app_name", "description", "app_type"]
                    }
                }
            },
            {
                "type": "function",
                "function": {
                    "name": "generate_code_file",
                    "description": "Generate any code file (Python, JavaScript, HTML, CSS, etc.) based on description",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "filename": {"type": "string", "description": "Name of the file to create (e.g., 'script.py', 'index.html')"},
                            "description": {"type": "string", "description": "What the code should do"},
                            "language": {"type": "string", "description": "Programming language: 'python', 'javascript', 'html', 'css', 'java', etc."}
                        },
                        "required": ["filename", "description", "language"]
                    }
                }
            }
        ]

    def get_functions(self) -> Dict[str, Callable]:
        return {
            "create_fullstack_website": self.create_fullstack_website,
            "create_python_app": self.create_python_app,
            "generate_code_file": self.generate_code_file
        }

    def create_fullstack_website(self, project_name, description, tech_stack="react"):
        try:
            # Create project directory
            project_path = os.path.join(os.path.expanduser("~"), "Desktop", project_name)
            os.makedirs(project_path, exist_ok=True)
            
            if tech_stack.lower() == "react":
                # Create React app
                result = subprocess.run(
                    ["npx", "create-react-app", project_name],
                    cwd=os.path.join(os.path.expanduser("~"), "Desktop"),
                    capture_output=True,
                    text=True,
                    timeout=300
                )
                
                if result.returncode == 0:
                    # Add custom README
                    readme_content = f"""# {project_name}

## Description
{description}

## Tech Stack
- React
- JavaScript
- CSS

## Setup
```bash
npm install
npm start
```

## Features
This website was automatically generated by JARVIS AI.
"""
                    with open(os.path.join(project_path, "README.md"), "w") as f:
                        f.write(readme_content)
                    
                    return json.dumps({
                        "status": "success",
                        "message": f"React website '{project_name}' created successfully!",
                        "path": project_path,
                        "next_steps": f"cd {project_path} && npm start"
                    })
            
            else:
                # Create vanilla HTML/CSS/JS website
                os.makedirs(os.path.join(project_path, "css"), exist_ok=True)
                os.makedirs(os.path.join(project_path, "js"), exist_ok=True)
                
                # Generate HTML
                html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{project_name}</title>
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <div class="container">
        <h1>{project_name}</h1>
        <p>{description}</p>
        <div id="app"></div>
    </div>
    <script src="js/script.js"></script>
</body>
</html>"""
                
                # Generate CSS
                css_content = """* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    min-height: 100vh;
    display: flex;
    justify-content: center;
    align-items: center;
}

.container {
    background: white;
    padding: 2rem;
    border-radius: 10px;
    box-shadow: 0 10px 30px rgba(0,0,0,0.3);
    max-width: 800px;
    width: 90%;
}

h1 {
    color: #667eea;
    margin-bottom: 1rem;
}

p {
    color: #666;
    line-height: 1.6;
}"""
                
                # Generate JavaScript
                js_content = """// JARVIS Auto-Generated JavaScript
console.log('Website initialized by JARVIS AI');

document.addEventListener('DOMContentLoaded', function() {
    const app = document.getElementById('app');
    app.innerHTML = '<p>This website was automatically created by JARVIS AI Assistant!</p>';
});"""
                
                # Write files
                with open(os.path.join(project_path, "index.html"), "w") as f:
                    f.write(html_content)
                with open(os.path.join(project_path, "css", "style.css"), "w") as f:
                    f.write(css_content)
                with open(os.path.join(project_path, "js", "script.js"), "w") as f:
                    f.write(js_content)
                
                # Open in browser
                subprocess.run(["open", os.path.join(project_path, "index.html")])
                
                return json.dumps({
                    "status": "success",
                    "message": f"Website '{project_name}' created and opened in browser!",
                    "path": project_path,
                    "files": ["index.html", "css/style.css", "js/script.js"]
                })
                
        except Exception as e:
            return json.dumps({"status": "error", "error": str(e)})

    def create_python_app(self, app_name, description, app_type):
        try:
            # Create app directory
            app_path = os.path.join(os.path.expanduser("~"), "Desktop", app_name)
            os.makedirs(app_path, exist_ok=True)
            
            # Generate main Python file based on type
            if app_type == "gui":
                code = f'''"""
{app_name} - {description}
Auto-generated by JARVIS AI
"""

import tkinter as tk
from tkinter import ttk, messagebox

class {app_name.replace(" ", "")}App:
    def __init__(self, root):
        self.root = root
        self.root.title("{app_name}")
        self.root.geometry("600x400")
        
        # Main frame
        main_frame = ttk.Frame(root, padding="10")
        main_frame.grid(row=0, column=0, sticky=(tk.W, tk.E, tk.N, tk.S))
        
        # Title
        title_label = ttk.Label(main_frame, text="{app_name}", font=("Arial", 16, "bold"))
        title_label.grid(row=0, column=0, pady=10)
        
        # Description
        desc_label = ttk.Label(main_frame, text="{description}", wraplength=500)
        desc_label.grid(row=1, column=0, pady=10)
        
        # Action button
        action_btn = ttk.Button(main_frame, text="Click Me", command=self.on_action)
        action_btn.grid(row=2, column=0, pady=20)
        
    def on_action(self):
        messagebox.showinfo("Success", "Action completed!")

if __name__ == "__main__":
    root = tk.Tk()
    app = {app_name.replace(" ", "")}App(root)
    root.mainloop()
'''
            elif app_type == "cli":
                code = f'''"""
{app_name} - {description}
Auto-generated by JARVIS AI
"""

import argparse
import sys

def main():
    parser = argparse.ArgumentParser(description="{description}")
    parser.add_argument("--action", help="Action to perform", default="run")
    args = parser.parse_args()
    
    print(f"{{app_name}} - Running...")
    print(f"Description: {description}")
    print(f"Action: {{args.action}}")
    
    # Add your logic here
    print("Task completed successfully!")

if __name__ == "__main__":
    main()
'''
            else:  # automation
                code = f'''"""
{app_name} - {description}
Auto-generated by JARVIS AI
"""

import time
import os

def main():
    print(f"{app_name} - Automation Script")
    print(f"Description: {description}")
    print("Starting automation...")
    
    # Add your automation logic here
    time.sleep(1)
    print("Automation completed successfully!")

if __name__ == "__main__":
    main()
'''
            
            # Write main file
            main_file = os.path.join(app_path, "main.py")
            with open(main_file, "w") as f:
                f.write(code)
            
            # Create requirements.txt
            requirements = ""
            if app_type == "gui":
                requirements = "# GUI dependencies\n# tkinter comes with Python\n"
            
            with open(os.path.join(app_path, "requirements.txt"), "w") as f:
                f.write(requirements)
            
            # Create README
            readme = f"""# {app_name}

{description}

## Type
{app_type.upper()} Application

## Setup
```bash
pip install -r requirements.txt
python main.py
```

## Auto-generated by JARVIS AI
This application was automatically created by JARVIS AI Assistant.
"""
            with open(os.path.join(app_path, "README.md"), "w") as f:
                f.write(readme)
            
            # Run the app
            subprocess.Popen(["python3", main_file])
            
            return json.dumps({
                "status": "success",
                "message": f"Python {app_type} app '{app_name}' created and launched!",
                "path": app_path,
                "main_file": "main.py"
            })
            
        except Exception as e:
            return json.dumps({"status": "error", "error": str(e)})

    def generate_code_file(self, filename, description, language):
        try:
            # Generate code based on language and description
            code_templates = {
                "python": f'''"""
{description}
Auto-generated by JARVIS AI
"""

def main():
    print("Running {filename}...")
    # Add your code here
    pass

if __name__ == "__main__":
    main()
''',
                "javascript": f'''/**
 * {description}
 * Auto-generated by JARVIS AI
 */

function main() {{
    console.log("Running {filename}...");
    // Add your code here
}}

main();
''',
                "html": f'''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{filename}</title>
</head>
<body>
    <h1>{description}</h1>
    <!-- Auto-generated by JARVIS AI -->
</body>
</html>
''',
                "css": f'''/* {description} */
/* Auto-generated by JARVIS AI */

* {{
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}}

body {{
    font-family: Arial, sans-serif;
}}
'''
            }
            
            code = code_templates.get(language.lower(), f"// {description}\n// Auto-generated by JARVIS AI\n")
            
            # Save to Desktop
            file_path = os.path.join(os.path.expanduser("~"), "Desktop", filename)
            with open(file_path, "w") as f:
                f.write(code)
            
            # Open in default editor
            subprocess.run(["open", file_path])
            
            return json.dumps({
                "status": "success",
                "message": f"Code file '{filename}' created and opened!",
                "path": file_path,
                "language": language
            })
            
        except Exception as e:
            return json.dumps({"status": "error", "error": str(e)})
